version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/src/app
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    build: ./app
    restart: always
    image: diggers_websource
    command: gunicorn diggers.wsgi -b 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    expose:
      - "8000"
    env_file:
      - .env
