version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - local

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      SITE_NAME: Acis urban exploration site
      SITE_DOMAIN: diggers.kiev.ua
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - local

  pgadmin:
    build: ./build/pgadmin/
    links:
      - postgres:postgres
    container_name: pgadmin
    volumes:
       - ./data/pgadmin/.pgadmin:/root/.pgadmin
       - ./data/pgadmin/storage:/var/lib/pgadmin/storage/pgadmin4
    ports:
      - "5050:5050"
    networks:
      - local
    restart: always

  web:
    build: .
    restart: always
    image: websource
    command: gunicorn acis.wsgi -b 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - local

  postfix:
    build: ./build/postfix/
    restart: always
    container_name: postfix
    environment:
      - DOMAINS=diggers.kiev.ua localhost
    ports:
      - "25:25"
    depends_on:
      - web
    volumes:
      - ./config/opendkim:/etc/opendkim
    networks:
      - local

  redis:
    build: ./build/redis
    command: redis-server
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - local

volumes:
  postgres_data:
  redis_data:

networks:
  local:
    driver: bridge