version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/src/app
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    depends_on:
      - app
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app:
    build: ./app
    restart: always
    image: diggers_websource
    command: gunicorn diggers.wsgi -b 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - postgres
      - postfix
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: always
    environment:
      SITE_NAME: Kiev urban exploration site
      SITE_DOMAIN: diggers.kiev.ua
    volumes:
      - ./postgres:/root
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  postfix:
    build: ./postfix/
    restart: always
    container_name: postfix
    command: /usr/bin/supervisord -c /supervisord.conf
    ports:
      - "25:25"
    volumes:
      - ./opendkim:/etc/opendkim
    env_file:
      - .env

volumes:
  postgres_data:
