version: '2'

services:
  web:
    build: .
    restart: always
    image: websource
    command: gunicorn acis.wsgi -b 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - local

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
      - ./nginx:/etc/nginx/conf.d
    networks:
      - local

networks:
  local:
    driver: bridge