version: '3'

services:
  postgres:
    image: postgres:10.1
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    image: websource
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: