version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    image: websource
    command: >
      bash -c "gunicorn acis.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - postgres

volumes:
  postgres_data: