version: '2'

services:
  web:
    build: .
    image: websource
    container_name: "diggers_websource_local"
    command: gunicorn acis.wsgi -b 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - localnet
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
      - ./nginx:/etc/nginx/conf.d
    networks:
      - localnet

networks:
  localnet:
    external:
      name: diggers-local