version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - local

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      SITE_NAME: Acis urban exploration site
      SITE_DOMAIN: diggers.kiev.ua
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - local

  pgadmin:
    build: ./config/pgadmin/
    links:
      - postgres:postgres
    container_name: pgadmin
    volumes:
       - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - local
    restart: always

  web:
    build: .
    restart: always
    image: websource
    command: gunicorn acis.wsgi -b 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - local

  postfix:
    build: ./config/postfix/
    restart: always
    container_name: postfix
    command: /usr/bin/supervisord -c /supervisord.conf
    environment:
      - DOMAINS=diggers.kiev.ua localhost
    ports:
      - "25:25"
    depends_on:
      - web
    volumes:
      - opendkim_keys:/etc/opendkim/keys
    networks:
      - local

volumes:
  postgres_data:
  opendkim_keys:

networks:
  local:
    driver: bridge