version: '2'

services:
  web:
    container_name: "diggers_websource"
    build: .
    image: websource
    restart: on-failure
    command: gunicorn acis.wsgi -b 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./:/usr/src/app
    expose:
      - "8000"
    networks:
      - diggers-websource-localnet
      - diggers-external

  nginx:
    container_name: "diggers_websource_proxy"
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
      - ./nginx:/etc/nginx/conf.d
    networks:
      - diggers-websource-localnet

networks:
  diggers-websource-localnet:
    driver: bridge
  diggers-external:
    external: true