# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_comment_moderate', 'Модерация комментариев'),), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post_moderate', 'Модерация постов'),), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_profile_moderate', 'Модерация профилей'),), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
