# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-02 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmspost',
            name='published_date',
        ),
    ]
