# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmscategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='cmspost',
            options={'permissions': (('moderate_cmspost', 'Модерація постів'), ('permited_access', 'Доступ до прихованих постів')), 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('moderate_comment', 'Модерація коментарів'),), 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_moderated',
        ),
        migrations.AddField(
            model_name='cmspost',
            name='modifed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='cmscategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='cmscategory',
            name='route',
            field=models.CharField(max_length=200, verbose_name='Шлях'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.CmsCategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='is_permited',
            field=models.BooleanField(default=False, verbose_name='Зробити прихованим'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modifed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Comment', verbose_name='Відповідь на'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=simplemde.fields.SimpleMDEField(verbose_name='Текст'),
        ),
    ]
