# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190615_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsprofile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
        migrations.AddField(
            model_name='cmsprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('BOY', 'Хлопець'), ('GIRL', 'Дівчина')], max_length=10, null=True, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='cmsprofile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='cmsprofile',
            name='email_change_token',
            field=models.CharField(max_length=42, verbose_name='Код підтвердження зміни e-mail'),
        ),
        migrations.AlterField(
            model_name='cmsprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Був на сайті'),
        ),
        migrations.AlterField(
            model_name='cmsprofile',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Місце розташування'),
        ),
        migrations.AlterField(
            model_name='cmsprofile',
            name='new_email',
            field=models.CharField(max_length=256, verbose_name='Новий e-mail'),
        ),
    ]
