# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190616_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsprofile',
            name='email_verefied',
            field=models.BooleanField(default=False, verbose_name='Підтвердити e-mail користувача'),
        ),
    ]
