# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-06 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_cmscategory_i18n_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmscategory',
            name='i18n_name_plural',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Перевод названия в единичном числе'),
        ),
    ]
