# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20171206_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binarypost',
            options={'permissions': (('moderate_binarypost', 'Модерация изображений'),), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='textpost',
            options={'permissions': (('moderate_textpost', 'Модерация текстовых постов'),), 'verbose_name': 'Текстовый пост', 'verbose_name_plural': 'Текстовые посты'},
        ),
    ]
