# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0008_auto_20180709_2221'),
        ('auth', '0008_alter_user_username_max_length'),
        ('cms', '0004_cmscategory_i18n_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pybb.Forum')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Группы имеющие доступ')),
            ],
            options={
                'verbose_name': 'Группы форума',
                'verbose_name_plural': 'Группы форума',
                'permissions': (('change_forumn_access', 'Изменение доступа к закрытым форумам'),),
            },
        ),
    ]
