# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-25 05:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20171207_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarypost',
            name='file',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='category',
            name='allow_anonymous',
            field=models.BooleanField(default=True, help_text='Установка этой галочки отключает контроль доступа к категории по группам пользователя', verbose_name='Полный доступ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='route',
            field=models.CharField(help_text='<font color="red">Внимание! Изменение этого поля у существующих категорий может повлиять на логику работы!</font>', max_length=200, verbose_name='Название в URL'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
