# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_cmsprofile_email_verefied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsprofile',
            name='new_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Новий e-mail'),
        ),
    ]
