# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180425_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('moderate_post', 'Модерация постов'), ('publish_post', 'Публикация постов')), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
