# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-21 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0006_auto_20180514_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=42, verbose_name='Код подтверждения')),
                ('new_email', models.CharField(max_length=256, verbose_name='Новый email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
