# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20171127_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='comment',
            name='modifed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
