# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20181216_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='new_email',
            field=models.CharField(max_length=256, verbose_name='New e-mail'),
        ),
    ]
