# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0009_auto_20171130_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_avatar', models.BooleanField(default=False)),
                ('birth_date', models.CharField(blank=True, max_length=80, null=True, verbose_name='Дата рождения')),
                ('location', models.CharField(blank=True, max_length=80, null=True, verbose_name='Местонахождение')),
                ('site', models.CharField(blank=True, max_length=80, null=True, verbose_name='Вебсайт')),
                ('facebook', models.CharField(blank=True, max_length=80, null=True, verbose_name='Facebook')),
                ('vk', models.CharField(blank=True, max_length=80, null=True, verbose_name='Vkontakte')),
                ('instagram', models.CharField(blank=True, max_length=80, null=True, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=80, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(blank=True, max_length=80, null=True, verbose_name='YouTube')),
                ('jabber', models.CharField(blank=True, max_length=80, null=True, verbose_name='Jabber')),
                ('telegram', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telegram')),
                ('skype', models.CharField(blank=True, max_length=80, null=True, verbose_name='Skype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
