# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20181229_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsprofile',
            name='hide_email',
            field=models.BooleanField(default=False, verbose_name='Hide email'),
        ),
    ]
