# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_cmsprofile_hide_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsprofile',
            name='hide_email',
            field=models.BooleanField(default=False, verbose_name='Hide e-mail'),
        ),
    ]
