# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20181229_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsprofile',
            name='hide_email',
            field=models.BooleanField(default=True, verbose_name='Приховати e-mail'),
        ),
    ]
