# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190510_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumgroups',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='autosubscribe',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='show_signatures',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='signature_html',
        ),
        migrations.RemoveField(
            model_name='cmsprofile',
            name='time_zone',
        ),
        migrations.DeleteModel(
            name='ForumGroups',
        ),
    ]
