# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmspostunread_commentunread'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspost',
            name='last_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Comment', verbose_name='Останній коментар'),
        ),
    ]
