# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_cmsprofile_is_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsprofile',
            old_name='email_verefied',
            new_name='email_verified',
        ),
    ]
